//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BITSoccer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class About
    {
        public int About_ID { get; set; }
        public string Name { get; set; }
        public string MetaTitle { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string About_Image { get; set; }
        public string Content { get; set; }
        public int About_Slide_ID { get; set; }
    
        public virtual About_Slide About_Slide { get; set; }
    }
}
