//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BITSoccer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.BillDetails = new HashSet<BillDetail>();
        }
    
        public int Bill_ID { get; set; }
        public int User_ID { get; set; }
        public Nullable<System.DateTime> DatePay { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> TotalPaid { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<bool> VISAPay { get; set; }
        public Nullable<bool> ATMPay { get; set; }
        public Nullable<bool> MoMoPay { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillDetail> BillDetails { get; set; }
        public virtual User User { get; set; }
    }
}
