//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BITSoccer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillDetail
    {
        public int BillDetailID { get; set; }
        public Nullable<int> BillID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<System.DateTime> DateSignIN { get; set; }
        public Nullable<System.DateTime> DateExpierd { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Class Class { get; set; }
    }
}
