//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BITSoccer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BITSoccerEntities : DbContext
    {
        public BITSoccerEntities()
            : base("name=BITSoccerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Archive> Archives { get; set; }
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<BillDetail> BillDetails { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Coach> Coaches { get; set; }
        public virtual DbSet<Coach_Moment> Coach_Moment { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<DiscountCode> DiscountCodes { get; set; }
        public virtual DbSet<Footer> Footers { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Header> Headers { get; set; }
        public virtual DbSet<Home_Slide> Home_Slide { get; set; }
        public virtual DbSet<HomePage_Content> HomePage_Content { get; set; }
        public virtual DbSet<LevelCoach> LevelCoaches { get; set; }
        public virtual DbSet<LevelStudent> LevelStudents { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<News_Category> News_Category { get; set; }
        public virtual DbSet<PartOfDay> PartOfDays { get; set; }
        public virtual DbSet<RangeAge> RangeAges { get; set; }
        public virtual DbSet<RangeTime> RangeTimes { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<Stadium> Stadia { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<Tourament> Touraments { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<About_Slide> About_Slide { get; set; }
    }
}
