//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BITSoccer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coach_Moment
    {
        public int Coach_Moment_ID { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public string Link { get; set; }
    }
}
