//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BITSoccer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comment()
        {
            this.Comment1 = new HashSet<Comment>();
            this.Comment11 = new HashSet<Comment>();
        }
    
        public int Comment_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Class_ID { get; set; }
        public Nullable<int> New_ID { get; set; }
        public Nullable<int> RootCommentID { get; set; }
        public Nullable<int> ReplyToCommentID { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual News News { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment1 { get; set; }
        public virtual Comment Comment2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment11 { get; set; }
        public virtual Comment Comment3 { get; set; }
    }
}
