//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BITSoccer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DiscountCode
    {
        public int DiscountCodeID { get; set; }
        public string DiscountCode1 { get; set; }
        [Range(0.1,0.9,ErrorMessage ="Chỉ nhận giá trị từ 0.1 đến 0.9")]
        public Nullable<double> Discount { get; set; }
    }
}
