//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BITSoccer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomePage_Content
    {
        public int Home_Content_ID { get; set; }
        public string Coach_Content { get; set; }
        public string HotClass_Content { get; set; }
        public string Tour_Content { get; set; }
        public string Stadium_Content { get; set; }
        public string Archive_Content { get; set; }
        public string Quote1_Content { get; set; }
        public string Quote2_Content { get; set; }
    }
}
