//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BITSoccer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsTag
    {
        public int NewsTagsID { get; set; }
        public Nullable<int> NewsID { get; set; }
        public Nullable<int> TagsID { get; set; }
    
        public virtual News News { get; set; }
        public virtual News News1 { get; set; }
        public virtual News News2 { get; set; }
        public virtual Tag Tag { get; set; }
        public virtual Tag Tag1 { get; set; }
        public virtual Tag Tag2 { get; set; }
    }
}
