//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BITSoccer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int RatingID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Class_ID { get; set; }
        public Nullable<int> NumberStar { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual User User { get; set; }
    }
}
