//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BITSoccer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tourament
    {
        public int Tour_ID { get; set; }
        public string Name { get; set; }
        public string MetaTitlte { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreaedBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Team_A { get; set; }
        public string Team_B { get; set; }
        public Nullable<int> Team_A_Score { get; set; }
        public Nullable<int> Team_B_Score { get; set; }
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm:ss}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Time { get; set; }
        public int Stadium_ID { get; set; }
        public string Team_A_Player { get; set; }
        public string Team_B_Player { get; set; }
        public Nullable<int> TeamARedCard { get; set; }
        public Nullable<int> TeamAYellowCart { get; set; }
        public Nullable<int> TeamAFouls_Conceded { get; set; }
        public Nullable<int> TeamBRedCard { get; set; }
        public Nullable<int> TeamBYellowCart { get; set; }
        public Nullable<int> TeamBFouls_Conceded { get; set; }
        public string TeamAFormation { get; set; }
        public string TeamBFormation { get; set; }
    
        public virtual Stadium Stadium { get; set; }
    }
}
